### PR TITLE
README.md: fix links, line wraps

### PR DESCRIPTION
**Pull request by kerstin**
(removed manual line wrapping because keeping it in order when editing files collaboratively is difficult)

### CODE REVIEW

**Comment by XaF** [comment]
I'm not sure I agree with the removal of the line wrapping, as I feel like a README file should be readable easily even without it being rendered in Markdown, and even without an editor that does wrapping for you. Reading the file as-is in a really large console wouldn't be comfortable!

**Comment by kerstin** [comment]
I've never seen manual line breaks in READMEs before – except maybe in a handful of Python projects where the README got derived from another file format (rst) – so would assume most people use READMEs differently (or know how to set their console's width), but sure, can refactor these changes.

**Comment by kerstin** [comment]
See update from my side re: word wrap/line breaks in #82.

**Comment by XaF** [comment]
TraktForVLC 2.x makes that PR obsolete - #88

**Pull request closed without merging**
