### PR TITLE
Fix.hide win shell

### PR DESCRIPTION
**Pull request by Foohx**
Hi,
Here is a small fix to hide the windows shell which is rather annoying.
Bye

### CODE REVIEW

**Comment by XaF** [comment]
These commits are kind of invasive on TraktForVLC as they are pushing the Windows approach of using ```.pyw``` extension, where Linux and OS X are not using it. A working approach that is not invasive is the use of ```pythonw.exe``` in the ```config.bat``` to hide the Windows console (when you use the ```start_process.bat``` script of course). I'll update the comment in this file specify the difference between using ```python.exe``` and ```pythonw.exe```.

Also, please be sure your branch is up to date with [master](https://github.com/XaF/TraktForVLC) before making a pull request, so it can be directly merged if accepted!

**Comment by Foohx** [comment]
Precisely the problem is that using `pythonw.exe` does not always work on `Windows` (My `Win7 x64` failed). This is why I proposed these modifications.

Therefore specify that it may be good to rename the file `TraktForVLC.py`. :)

**Comment by XaF** [comment]
Well, it should work, except if you're running manually the script by double-clicking on ```TraktForVLC.py```!
According to the way the OS works, having the ```.pyw``` extension just changes the default process used to run that Python script in Windows, but that process is only searched for if it's not already given in the command line (what we do with the ```.bat``` scripts provided in this repository). The [Python documentation](https://docs.python.org/2/using/windows.html#executing-scripts) also gives more information about that.

If it's not working without changing the extension, I would be interested to know what's really the running process in the background!

**Comment by Foohx** [comment]
So, I did a major clean and it works perfectly rigth now ...

Thanks for your time I close !

**Pull request closed without merging**
